### ISSUE TITLE
Linking local registration credentials to nodemailer

### ISSUE THREAD

**Issue by nvtekal** [matt-taggart/tone_analyzer#24]
If a user registers for our web application using OAuth, we can pass their username and password (encrypted) into a new nodemailer instance.  If they login locally, we either need to make sure that they use the same password for their email (shady and janky) or ask them to input their email credentials again anyways.  

Rgds,
Neelesh

**Comment by nvtekal** [comment]
4/19 Update: Disabled functionality if logged in locally.  Creates an incentive to use our OAuth service!!

**Comment by matt-taggart** [comment]
@ntekal Disabled this feature and closing
